M48
; DRILL file KiCad 10.0.3 date 2026-08-02T18:57:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-02T18:57:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X74.071Y-17.276
X74.139Y-92.283
X119.139Y-17.283
X119.139Y-92.283
M30
